name: Prewarm RSS Cache

on:
  schedule:
    - cron: "0 14 * * *"  # 每天 UTC 14:00，即日本時間 23:00
  workflow_dispatch:

jobs:
  trigger-netlify:
    runs-on: ubuntu-latest
    steps:
      - name: Curl RSS route to prewarm
        run: |
          TODAY=$(date '+%Y%m%d')
          curl --fail https://your-site.netlify.app/rss?date=$TODAY
